import { backend, ow } from "./client.js";
import { helloWorld } from "./hello-world.js";

// Run this file:
// JS: `node openworkflow/hello-world.run.js`
// TS: `npx tsx openworkflow/hello-world.run.ts`
//
// This file is a temporary dev helper generated by
// `npx @openworkflow/cli init` so you can quickly run the example workflow.
//
// Copy the code anywhere in your app (e.g., an API route or a script) and
// modify it to run your workflows.
//
// You can delete this file once you're done with it.

console.log("Running hello-world workflow...");
const handle = await ow.runWorkflow(helloWorld.spec, {});

console.log("Waiting for result...");
const result = await handle.result(); // for very short workflows only

console.log(`Workflow result: ${JSON.stringify(result, null, 2)}`);

// Stop backend. Only needed if this is a standalone script that you want to
// exit after running the workflow.
await backend.stop();
