import type { ProviderPreset } from '@/types';

export const TEXT_GEN_PRESETS: ProviderPreset[] = [
  {
    id: 'claude-text-api-key',
    name: 'Claude 文本',
    description: '适合知识库摘要、改写、标签等轻量文本场景。',
    provider_type: 'anthropic',
    api_protocol: 'anthropic-messages',
    capabilities: ['text-gen'],
    provider_origin: 'preset',
    auth_mode: 'api_key',
    base_url: 'https://api.anthropic.com',
    tags: ['知识库', '文本', 'Claude'],
    supported_modules: ['knowledge'],
  },
  {
    id: 'deepseek-text',
    name: 'DeepSeek',
    description: '深度求索大模型，性价比高，适合文本处理。',
    provider_type: 'custom',
    api_protocol: 'openai-compatible',
    capabilities: ['text-gen'],
    provider_origin: 'preset',
    auth_mode: 'api_key',
    base_url: 'https://api.deepseek.com',
    tags: ['知识库', '文本', 'OpenAI 兼容'],
    supported_modules: ['knowledge'],
  },
  {
    id: 'kimi-text',
    name: 'Kimi (Moonshot)',
    description: '月之暗面 Kimi 大模型，擅长长文本理解和生成。',
    provider_type: 'custom',
    api_protocol: 'openai-compatible',
    capabilities: ['text-gen'],
    provider_origin: 'preset',
    auth_mode: 'api_key',
    base_url: 'https://api.moonshot.cn/v1',
    tags: ['知识库', '文本', 'OpenAI 兼容'],
    supported_modules: ['knowledge'],
  },
  {
    id: 'zhipu-text',
    name: '智谱 GLM',
    description: '智谱 AI 大模型（ChatGLM），适合中文文本处理。',
    provider_type: 'custom',
    api_protocol: 'openai-compatible',
    capabilities: ['text-gen'],
    provider_origin: 'preset',
    auth_mode: 'api_key',
    base_url: 'https://open.bigmodel.cn/api/paas/v4',
    tags: ['知识库', '文本', 'OpenAI 兼容'],
    supported_modules: ['knowledge'],
  },
  {
    id: 'qwen-text',
    name: '通义千问 (Qwen)',
    description: '阿里云通义千问大模型。',
    provider_type: 'custom',
    api_protocol: 'openai-compatible',
    capabilities: ['text-gen'],
    provider_origin: 'preset',
    auth_mode: 'api_key',
    base_url: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    tags: ['知识库', '文本', 'OpenAI 兼容'],
    supported_modules: ['knowledge'],
  },
  {
    id: 'doubao-text',
    name: '豆包 (火山引擎)',
    description: '字节跳动豆包大模型，通过火山引擎 API 接入。',
    provider_type: 'custom',
    api_protocol: 'openai-compatible',
    capabilities: ['text-gen'],
    provider_origin: 'preset',
    auth_mode: 'api_key',
    base_url: 'https://ark.cn-beijing.volces.com/api/v3',
    tags: ['知识库', '文本', 'OpenAI 兼容'],
    supported_modules: ['knowledge'],
  },
  {
    id: 'baichuan-text',
    name: '百川',
    description: '百川智能大模型。',
    provider_type: 'custom',
    api_protocol: 'openai-compatible',
    capabilities: ['text-gen'],
    provider_origin: 'preset',
    auth_mode: 'api_key',
    base_url: 'https://api.baichuan-ai.com/v1',
    tags: ['知识库', '文本', 'OpenAI 兼容'],
    supported_modules: ['knowledge'],
  },
  {
    id: 'yi-text',
    name: '零一万物 (Yi)',
    description: '零一万物 Yi 大模型。',
    provider_type: 'custom',
    api_protocol: 'openai-compatible',
    capabilities: ['text-gen'],
    provider_origin: 'preset',
    auth_mode: 'api_key',
    base_url: 'https://api.lingyiwanwu.com/v1',
    tags: ['知识库', '文本', 'OpenAI 兼容'],
    supported_modules: ['knowledge'],
  },
  {
    id: 'minimax-text',
    name: 'MiniMax',
    description: '稀宇科技 MiniMax 大模型。',
    provider_type: 'custom',
    api_protocol: 'openai-compatible',
    capabilities: ['text-gen'],
    provider_origin: 'preset',
    auth_mode: 'api_key',
    base_url: 'https://api.minimax.chat/v1',
    tags: ['知识库', '文本', 'OpenAI 兼容'],
    supported_modules: ['knowledge'],
  },
  {
    id: 'openrouter-text',
    name: 'OpenRouter',
    description: '多模型聚合网关，支持多家模型按需路由。',
    provider_type: 'openrouter',
    api_protocol: 'openai-compatible',
    capabilities: ['text-gen'],
    provider_origin: 'preset',
    auth_mode: 'api_key',
    base_url: 'https://openrouter.ai/api/v1',
    tags: ['知识库', '文本', 'OpenAI 兼容'],
    supported_modules: ['knowledge'],
  },
  {
    id: 'openai-compatible-text',
    name: '其他 OpenAI 兼容接口',
    description: '适合其他 OpenAI 兼容文本接口，手动填写 base URL。',
    provider_type: 'custom',
    api_protocol: 'openai-compatible',
    capabilities: ['text-gen'],
    provider_origin: 'preset',
    auth_mode: 'api_key',
    base_url: '',
    notes: '请填写 OpenAI 兼容接口的 base URL。SDK 会在此地址后拼接 /chat/completions。',
    tags: ['知识库', '文本', 'OpenAI 兼容'],
    supported_modules: ['knowledge'],
    requires_base_url: true,
  },
  {
    id: 'anthropic-compatible-text',
    name: '其他 Anthropic 兼容文本',
    description: '适合摘要、知识库等 text-gen 场景的 Anthropic Messages 兼容接口。',
    provider_type: 'custom',
    api_protocol: 'anthropic-messages',
    capabilities: ['text-gen'],
    provider_origin: 'preset',
    auth_mode: 'api_key',
    base_url: '',
    notes: '请填写可兼容 Anthropic Messages 协议的 base URL。',
    tags: ['知识库', '文本'],
    supported_modules: ['knowledge'],
    requires_base_url: true,
  },
];
