export const SQLITE_CLIENT = `import { BackendSqlite } from "openworkflow/sqlite";
import { OpenWorkflow } from "openworkflow";

export const backend = BackendSqlite.connect("openworkflow/backend.db");
export const ow = new OpenWorkflow({ backend });
`;

export const POSTGRES_CLIENT = `import { BackendPostgres } from "openworkflow/postgres";
import { OpenWorkflow } from "openworkflow";

export const backend = await BackendPostgres.connect(
  process.env["OPENWORKFLOW_POSTGRES_URL"],
);
export const ow = new OpenWorkflow({ backend });
`;

export const POSTGRES_PROD_SQLITE_DEV_CLIENT = `import { BackendPostgres } from "openworkflow/postgres";
import { BackendSqlite } from "openworkflow/sqlite";
import { OpenWorkflow } from "openworkflow";

export const backend =
  process.env["NODE_ENV"] === "production"
    ? await BackendPostgres.connect(process.env["OPENWORKFLOW_POSTGRES_URL"])
    : BackendSqlite.connect("openworkflow/backend.db");
export const ow = new OpenWorkflow({ backend });
`;

export const CONFIG = `import { backend } from "./openworkflow/client.js";
import { defineConfig } from "@openworkflow/cli";

export default defineConfig({
  backend,
  dirs: "./openworkflow",
  ignorePatterns: ["**/*.run.*"],
});
`;

export const HELLO_WORLD_WORKFLOW = `import { defineWorkflow } from "openworkflow";

/**
 * Example workflow that greets the world.
 *
 * This workflow is auto-discovered by the CLI worker.
 * To trigger it, use ow.runWorkflow() from your app:
 * \`\`\`ts
 * import { ow } from "./openworkflow/client.js";
 * import { helloWorld } from "./openworkflow/hello-world.js";
 * const handle = await ow.runWorkflow(helloWorld.spec, {});
 * const result = await handle.result();
 * \`\`\`
 */
export const helloWorld = defineWorkflow(
  { name: "hello-world" },
  async ({ step }) => {
    const greeting = await step.run({ name: "greet" }, () => {
      return "Hello, World!";
    });

    await step.sleep("wait-a-bit", "1s");

    return { greeting };
  },
);
`;

export const HELLO_WORLD_RUNNER = `import { backend, ow } from "./client.js";
import { helloWorld } from "./hello-world.js";

// Run this file:
// JS: \`node openworkflow/hello-world.run.js\`
// TS: \`npx tsx openworkflow/hello-world.run.ts\`
//
// This file is a temporary dev helper generated by
// \`npx @openworkflow/cli init\` so you can quickly run the example workflow.
//
// Copy the code anywhere in your app (e.g., an API route or a script) and
// modify it to run your workflows.
//
// You can delete this file once you're done with it.

console.log("Running hello-world workflow...");
const handle = await ow.runWorkflow(helloWorld.spec, {});

console.log("Waiting for result...");
const result = await handle.result(); // for very short workflows only

console.log(\`Workflow result: \${JSON.stringify(result, null, 2)}\`);

// Stop backend. Only needed if this is a standalone script that you want to
// exit after running the workflow.
await backend.stop();
`;
